"""
Multi-Agent LangGraph Workflow with Application Insights and Custom Tools

This script demonstrates LangChain/LangGraph multi-agent workflow using
the native langchain-azure-ai integration for Application Insights telemetry.

Architecture:
  User Query
      │
      ▼
  ┌─────────────┐  Tools:          ┌─────────────────┐  Tools:
  │  Researcher │  - search_web    │  Summarizer     │  - format_article
  │   Agent     │  - statistics    │   Agent         │  - add_citations
  │             │  - verify_facts  │                 │
  └─────────────┘                  └─────────────────┘
      │                                     │
      └───────────── Traces ────────────────┘
                        │
                        ▼
              Application Insights

Observability Approach:
- AzureAIOpenTelemetryTracer: Automatic tracing via LangChain callbacks
- trace_all_langgraph_nodes=True: CRITICAL parameter for proper LangGraph tracing
- NO custom OpenTelemetry spans - the tracer handles everything through callbacks
- Callback-based instrumentation automatically creates spans for:
  * LangGraph workflow execution
  * Each agent node invocation (with proper timing when trace_all_langgraph_nodes=True)
  * Each LLM call (with GenAI semantic conventions)
  * Each tool execution
  
Expected trace hierarchy (auto-generated by tracer with trace_all_langgraph_nodes=True):
    LangGraph workflow
    ├── invoke_agent researcher
    │   ├── chat (LLM call with gen_ai.* attributes)
    │   ├── execute_tool search_web
    │   ├── execute_tool gather_statistics
    │   └── chat (final response)
    └── invoke_agent summarizer
        ├── chat (LLM call)
        ├── execute_tool format_article
        └── chat (final response)

Key Pattern:
- Uses LangGraph's ToolNode for automatic tool execution
- Proper ToolMessage responses with tool_call_id
- Conditional routing between agents and tools
- All traces captured automatically by AzureAIOpenTelemetryTracer
- Connection string prevents managed identity token calls (avoids NewConnectionError)
"""

import os
import time
from typing import Annotated
from random import randint

from dotenv import load_dotenv
from azure.identity import DefaultAzureCredential, get_bearer_token_provider

# ── LangChain Azure AI Tracer ────────────────────────────────────────────────
from langchain_azure_ai.callbacks.tracers import AzureAIOpenTelemetryTracer

# ── LangGraph / LangChain ─────────────────────────────────────────────────────
from langgraph.graph import StateGraph, END, START, MessagesState
from langgraph.prebuilt import ToolNode
from langchain_openai import AzureChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.tools import tool

# Load environment variables
load_dotenv()


# ─────────────────────────────────────────────────────────────────────────────
# 0.  Custom Tools (automatically traced by AzureAIOpenTelemetryTracer via callbacks)
# ─────────────────────────────────────────────────────────────────────────────

@tool
def search_web(query: Annotated[str, "The search query to find information"]) -> str:
    """Search the web for information on a given topic."""
    # Simulate web search with delay
    time.sleep(randint(5, 15) / 10.0)
    
    # Simulate search results
    results = {
        "quantum computing": "Recent breakthroughs include Google's quantum supremacy demonstration, "
                            "IBM's 433-qubit Osprey processor, and advances in error correction codes. "
                            "Quantum computers are now solving problems classical computers cannot.",
        "photosynthesis": "Photosynthesis converts light energy into chemical energy through chlorophyll. "
                         "The process involves light-dependent and light-independent reactions, producing "
                         "glucose and oxygen from CO2 and water.",
        "climate change": "Global temperatures have risen 1.1°C since pre-industrial times. "
                         "The IPCC reports urgent action needed to limit warming to 1.5°C.",
        "artificial intelligence": "AI has advanced significantly with large language models, computer vision, "
                                  "and robotics. Applications span healthcare, autonomous vehicles, and more.",
    }
    
    for key in results:
        if key in query.lower():
            return f"🔍 Search results for '{query}':\n{results[key]}"
    
    return f"🔍 Search results for '{query}':\nGeneral information found. Multiple sources indicate growing interest in this area."


@tool
def gather_statistics(topic: Annotated[str, "The topic to gather statistics about"]) -> str:
    """Gather statistical data and facts about a topic."""
    # Simulate data gathering
    time.sleep(randint(3, 10) / 10.0)
    
    stats = {
        "quantum computing": "📊 Statistics:\n- Global quantum computing market: $1.3B (2024)\n"
                            "- Expected to reach $7.6B by 2030\n- 100+ quantum computers worldwide",
        "photosynthesis": "📊 Statistics:\n- Converts ~100 billion tons of CO2 annually\n"
                         "- Efficiency: 3-6% of sunlight energy captured\n- Produces ~170 billion tons O2/year",
        "climate change": "📊 Statistics:\n- Global CO2: 420 ppm\n- Sea level rise: 3.4mm/year\n"
                         "- Arctic ice decline: 13% per decade",
        "artificial intelligence": "📊 Statistics:\n- Global AI market: $136B (2024)\n"
                                  "- Expected growth: 37% CAGR\n- AI startups: 12,000+",
    }
    
    for key in stats:
        if key in topic.lower():
            return stats[key]
    
    return f"📊 Statistics for '{topic}':\nVarious metrics available. Growing trend observed."


@tool
def verify_facts(claim: Annotated[str, "The claim to verify"]) -> str:
    """Verify the accuracy of a claim or statement."""
    # Simulate fact-checking
    time.sleep(randint(2, 8) / 10.0)
    
    return f"✓ Fact-check: The claim '{claim[:50]}...' has been cross-referenced with reliable sources. Confidence: High."


@tool
def format_article(
    content: Annotated[str, "The content to format"],
    style: Annotated[str, "The writing style (formal, casual, technical)"] = "formal"
) -> str:
    """Format content as a well-structured article."""
    # Simulate formatting
    time.sleep(randint(2, 6) / 10.0)
    
    formatted = f"""
{'='*70}
FORMATTED ARTICLE ({style.upper()} STYLE)
{'='*70}

{content}

{'='*70}
✓ Article formatted and ready for publication
{'='*70}
"""
    return formatted


@tool
def add_citations(text: Annotated[str, "Text to add citations to"]) -> str:
    """Add proper citations and references to text."""
    # Simulate citation addition
    time.sleep(randint(1, 4) / 10.0)
    
    return f"{text}\n\n📚 References:\n[1] Recent peer-reviewed studies (2024-2026)\n[2] Academic journals and publications\n[3] Expert consensus reports"

# ─────────────────────────────────────────────────────────────────────────────
# 1.  Create the Azure AI OpenTelemetry Tracer
# ─────────────────────────────────────────────────────────────────────────────

def create_tracer() -> AzureAIOpenTelemetryTracer:
    """
    Create an AzureAIOpenTelemetryTracer that automatically sends traces
    to Application Insights.
    
    The tracer can be configured with:
    - connection_string: Direct Application Insights connection string
    - project_endpoint: Azure AI Project endpoint (auto-discovers App Insights)
    - enable_content_recording: Whether to include message content in traces
    - trace_all_langgraph_nodes: Enable proper LangGraph node tracing (IMPORTANT!)
    """
    
    # Prefer connection string to avoid managed identity token calls
    connection_string = os.getenv("APPLICATION_INSIGHTS_CONNECTION_STRING")
    
    if connection_string:
        print(f"[✓] Using direct Application Insights connection string")
        tracer = AzureAIOpenTelemetryTracer(
            connection_string=connection_string,
            enable_content_recording=True,  # Set False in production to redact content
            trace_all_langgraph_nodes=True,  # CRITICAL for LangGraph - enables proper node tracing
        )
    else:
        # Fallback to project endpoint (requires managed identity)
        project_endpoint = os.getenv("AZURE_AI_PROJECT_ENDPOINT")
        if project_endpoint:
            print(f"[✓] Using Azure AI Project endpoint: {project_endpoint}")
            tracer = AzureAIOpenTelemetryTracer(
                project_endpoint=project_endpoint,
                credential=DefaultAzureCredential(),
                enable_content_recording=True,
                trace_all_langgraph_nodes=True,  # CRITICAL for LangGraph
            )
        else:
            raise ValueError(
                "Either APPLICATION_INSIGHTS_CONNECTION_STRING or AZURE_AI_PROJECT_ENDPOINT "
                "must be set in environment variables"
            )
    
    print("[✓] LangChain Azure AI tracer configured")
    return tracer


# ─────────────────────────────────────────────────────────────────────────────
# 2.  Shared graph state
# ─────────────────────────────────────────────────────────────────────────────

# Use MessagesState from LangGraph - it manages conversation messages
# No need for custom state! MessagesState handles everything.


# ─────────────────────────────────────────────────────────────────────────────
# 3.  Define Custom Tools
# ─────────────────────────────────────────────────────────────────────────────

# Research tools for the Researcher agent
research_tools = [search_web, gather_statistics, verify_facts]

# Writing tools for the Summarizer agent
writing_tools = [format_article, add_citations]


# ─────────────────────────────────────────────────────────────────────────────
# 4.  Agent 1 – Researcher with Tools
# ─────────────────────────────────────────────────────────────────────────────

def make_researcher_agent(llm: AzureChatOpenAI):
    """
    Create researcher agent that uses research tools.
    Returns the bound model and a node function.
    """
    # Bind research tools to the LLM
    researcher_llm = llm.bind_tools(research_tools)
    
    def researcher_node(state: MessagesState):
        """
        Researcher agent node - automatically traced by AzureAIOpenTelemetryTracer.
        Tool calls are handled by ToolNode.
        No custom spans here - let LangChain's tracer handle everything.
        """
        print(f"\n{'─'*80}")
        print(f"[Researcher] Processing query...")
        
        messages = state["messages"]
        
        # Check if we've already used tools
        has_used_tools = any(hasattr(msg, '__class__') and msg.__class__.__name__ == 'ToolMessage' for msg in messages)
        
        # Add system message if this is the first message
        if not any(isinstance(msg, SystemMessage) for msg in messages):
            system_msg = SystemMessage(content=(
                "You are a research assistant with access to powerful research tools. "
                "IMPORTANT: You MUST use at least one tool to gather information. "
                "Available tools:\n"
                "- search_web: Search for current information and facts\n"
                "- gather_statistics: Get statistical data and numbers\n"
                "- verify_facts: Verify accuracy of claims\n\n"
                "ALWAYS start by calling search_web with the user's topic. "
                "After receiving tool results, provide a comprehensive research summary with 3-5 key findings."
            ))
            messages = [system_msg] + messages
        
        # If we've already used tools, force a final response without tools
        if has_used_tools:
            print(f"[Researcher] Tools already used, generating final research summary...")
            # Use LLM without tools to force final response
            final_instruction = HumanMessage(content=(
                "Now provide your comprehensive research summary based on all the tool results above. "
                "Do not call any more tools, just provide the summary with 3-5 key findings."
            ))
            response = llm.invoke(messages + [final_instruction])
        else:
            # First pass - allow tool use
            response = researcher_llm.invoke(messages)
        
        if hasattr(response, 'tool_calls') and response.tool_calls:
            print(f"[Researcher] Making {len(response.tool_calls)} tool call(s)...")
        else:
            print(f"[Researcher] Completed research.")
        
        return {"messages": [response]}
    
    return researcher_llm, researcher_node


# ─────────────────────────────────────────────────────────────────────────────
# 5.  Agent 2 – Summarizer with Tools
# ─────────────────────────────────────────────────────────────────────────────

def make_summarizer_agent(llm: AzureChatOpenAI):
    """
    Create summarizer agent that uses writing/formatting tools.
    Returns the bound model and a node function.
    """
    # Bind writing tools to the LLM
    summarizer_llm = llm.bind_tools(writing_tools)
    
    def summarizer_node(state: MessagesState):
        """
        Summarizer agent node - automatically traced by AzureAIOpenTelemetryTracer.
        Tool calls are handled by ToolNode.
        No custom spans here - let LangChain's tracer handle everything.
        """
        print(f"\n{'─'*80}")
        print(f"[Summarizer] Creating summary...")
        
        messages = state["messages"]
        
        # Check if we've already used tools in the summarizer phase
        has_used_tools = False
        summarizer_started = False
        for msg in messages:
            if hasattr(msg, 'content') and isinstance(msg.content, str) and 'Based on the research above' in msg.content:
                summarizer_started = True
            if summarizer_started and hasattr(msg, '__class__') and msg.__class__.__name__ == 'ToolMessage':
                has_used_tools = True
                break
        
        # If we haven't added the summary instruction yet, add it
        if not any(hasattr(msg, 'content') and isinstance(msg.content, str) and 'Based on the research above' in msg.content for msg in messages):
            summary_instruction = HumanMessage(content=(
                "Based on the research above, create a clear, engaging 2-3 sentence "
                "summary suitable for a general audience."
            ))
            messages = messages + [summary_instruction]
        
        # If we've already used tools, force a final response without tools
        if has_used_tools:
            print(f"[Summarizer] Tools already used, generating final summary...")
            # Use LLM without tools to force final response
            final_instruction = HumanMessage(content=(
                "Now provide your final summary based on all the information above. "
                "Do not call any more tools, just give the summary."
            ))
            response = llm.invoke(messages + [final_instruction])
        else:
            # First pass - allow tool use
            response = summarizer_llm.invoke(messages)
        
        if hasattr(response, 'tool_calls') and response.tool_calls:
            print(f"[Summarizer] Making {len(response.tool_calls)} tool call(s)...")
        else:
            print(f"[Summarizer] Completed summary.")
        
        return {"messages": [response]}
    
    return summarizer_llm, summarizer_node


# ─────────────────────────────────────────────────────────────────────────────
# 6.  Routing Logic
# ─────────────────────────────────────────────────────────────────────────────

def route_researcher(state: MessagesState):
    """Route from researcher: continue to tools or move to summarizer."""
    messages = state["messages"]
    last_message = messages[-1]
    # If the last message has tool calls, route to tools
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "researcher_tools"
    # Otherwise, move to summarizer
    return "summarizer"


def route_summarizer(state: MessagesState):
    """Route from summarizer: continue to tools or end."""
    messages = state["messages"]
    last_message = messages[-1]
    # If the last message has tool calls, route to tools
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "summarizer_tools"
    # Otherwise, we're done
    return "end"


# ─────────────────────────────────────────────────────────────────────────────
# 7.  Build and compile the LangGraph workflow
# ─────────────────────────────────────────────────────────────────────────────

def build_workflow(llm: AzureChatOpenAI):
    """
    Assembles the multi-agent graph with automatic tool execution:
    
    START → researcher → [tools?] → summarizer → [tools?] → END
    
    Uses ToolNode to automatically handle tool calls with proper ToolMessage
    responses including tool_call_id.
    """
    # Create agents
    researcher_llm, researcher_node = make_researcher_agent(llm)
    summarizer_llm, summarizer_node = make_summarizer_agent(llm)
    
    # Create ToolNodes for automatic tool execution
    researcher_tool_node = ToolNode(research_tools)
    summarizer_tool_node = ToolNode(writing_tools)
    
    # Build the graph
    workflow = StateGraph(MessagesState)
    
    # Add agent nodes
    workflow.add_node("researcher", researcher_node)
    workflow.add_node("summarizer", summarizer_node)
    
    # Add tool nodes
    workflow.add_node("researcher_tools", researcher_tool_node)
    workflow.add_node("summarizer_tools", summarizer_tool_node)
    
    # Set entry point
    workflow.add_edge(START, "researcher")
    
    # Add conditional edges from researcher
    workflow.add_conditional_edges(
        "researcher",
        route_researcher,
        {
            "researcher_tools": "researcher_tools",
            "summarizer": "summarizer",
        }
    )
    
    # After researcher tools, go back to researcher
    workflow.add_edge("researcher_tools", "researcher")
    
    # Add conditional edges from summarizer
    workflow.add_conditional_edges(
        "summarizer",
        route_summarizer,
        {
            "summarizer_tools": "summarizer_tools",
            "end": END,
        }
    )
    
    # After summarizer tools, go back to summarizer
    workflow.add_edge("summarizer_tools", "summarizer")
    
    return workflow.compile()


# ─────────────────────────────────────────────────────────────────────────────
# 8.  Run the workflow with the tracer
# ─────────────────────────────────────────────────────────────────────────────

def run_workflow(query: str, app, tracer: AzureAIOpenTelemetryTracer) -> dict:
    """
    Run the workflow with the AzureAIOpenTelemetryTracer.
    The tracer automatically creates spans for all operations via LangChain callbacks.
    
    NO custom parent span - let the tracer create the proper hierarchy automatically.
    """
    print(f"\n{'═'*80}")
    print(f" LangGraph Multi-Agent Workflow with Tools")
    print(f"{'═'*80}")
    print(f" Query: {query}")

    try:
        # Initial state with the user query
        initial_state = {"messages": [HumanMessage(content=query)]}

        # Pass the tracer via config callbacks - this is the key!
        # The tracer will automatically create spans for:
        # - LangGraph workflow execution
        # - Each agent node invocation
        # - Each LLM call (with GenAI semantic conventions)
        # - Each tool execution
        config = {"callbacks": [tracer]}
        
        start = time.monotonic()
        result = app.invoke(initial_state, config=config)
        elapsed = time.monotonic() - start

        # Extract final message
        final_message = result["messages"][-1]
        final_content = final_message.content if hasattr(final_message, 'content') else str(final_message)
        
        # Count tool uses
        tool_messages = [msg for msg in result["messages"] if hasattr(msg, '__class__') and msg.__class__.__name__ == 'ToolMessage']
        tools_used = len(tool_messages)
        
        print(f"\n{'═'*80}")
        print(" FINAL RESULT")
        print(f"{'═'*80}")
        print(final_content)
        print(f"\n Tools Executed: {tools_used}")
        print(f" Completed in {elapsed:.2f}s")
        print(f"{'═'*80}\n")

        return result
        
    except Exception as e:
        print(f"[!] Workflow error: {e}")
        raise


# ─────────────────────────────────────────────────────────────────────────────
# 9.  Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    """Main execution function"""
    
    print("\n" + "="*80)
    print("LANGCHAIN/LANGGRAPH MULTI-AGENT WORKFLOW WITH TOOLS")
    print("="*80)
    print("Using langchain-azure-ai native Application Insights integration")
    print("Key setting: trace_all_langgraph_nodes=True for proper node tracing")
    print("Tools: search_web, gather_statistics, verify_facts, format_article, add_citations")
    print("="*80 + "\n")
    
    # Create the Azure AI OpenTelemetry Tracer
    tracer = create_tracer()
    
    # Initialize Azure OpenAI LLM with token provider for authentication
    token_provider = get_bearer_token_provider(
        DefaultAzureCredential(),
        "https://cognitiveservices.azure.com/.default"
    )
    
    llm = AzureChatOpenAI(
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        azure_deployment=os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT"),
        api_version=os.getenv("AZURE_OPENAI_VERSION", "2024-08-01-preview"),
        azure_ad_token_provider=token_provider,
        temperature=0.3,
    )
    
    # Build the compiled LangGraph app
    app = build_workflow(llm)
    
    # Run sample queries that will definitely trigger tool use
    queries = [
        "Search for the latest breakthroughs in quantum computing and provide statistics on market growth.",
        # More explicit query to ensure tool calling
    ]
    
    for q in queries:
        try:
            run_workflow(q, app, tracer)
            time.sleep(1)  # Brief pause between workflows
        except Exception as e:
            print(f"[!] Workflow failed for query '{q}': {e}")
            continue
    
    print("\n" + "="*80)
    print("ALL WORKFLOWS COMPLETED")
    print("Check Application Insights for detailed telemetry data")
    print("="*80 + "\n")


if __name__ == "__main__":
    main()
